export const BookGenres: string[] = [
    'Mystery',
    'Thriller',
    'Science Fiction',
    'Fantasy',
    'Romance',
    'Historical fiction',
    'Dystopian',
    'Adventure',
    'Western',
    'Biography/Autobiography',
    'Memoir',
    'History',
    'Self-help / Personal',
    'True Crime',
    'Science',
    'Travel',
    'Cookbooks',
    'Essay',
    'Picture books',
    'Middle grade',
    'Young adult',
    'Poetry',
    'Horror',
    'Graphic Novels/Comics',
    'Religious/Spiritual',
    'Classics',
    'Biographical Fiction',
    'Satire',
];

export const Genres: { genre: IBookStrings; displayName: string }[] = [
    {
        genre: 'modern',
        displayName: 'Modern',
    },
    {
        genre: 'agathe',
        displayName: 'Mystery',
    },
    {
        genre: 'classic',
        displayName: 'Classics',
    },
    {
        genre: 'zen',
        displayName: 'Zen',
    },
    {
        genre: 'dad',
        displayName: 'Family',
    },
];

export const bookData: Record<IBookStrings, { query: string; books: IBookData[] }> = {
    modern: {
        query: 'What is a must read book in 2023',
        books: [
            {
                title: 'The Fraud',
                authors: 'Zadie Smith',
                price: 26.97,
                publisher: 'Penguin Press',
                num_pages: 464,
                publish_date: 'September 05, 2023',
                average_rating: 3.5,
                reviews: 2456,
                is_staff_pick: false,
                pic: require('../assets/images/covers/zadie.jpg'),
            },
            {
                title: 'The Bee Sting',
                authors: 'Paul Murray',
                price: 27.9,
                price_before: 35.9,
                publisher: 'Farrar, Straus and Giroux',
                num_pages: 656,
                publish_date: 'August 15, 2023',
                average_rating: 4.1,
                reviews: 2940,
                is_staff_pick: true,
                pic: require('../assets/images/covers/murray.jpg'),
            },
            {
                title: 'Crook Manifesto',
                authors: 'Colson Whitehead',
                price: 28.83,
                publisher: 'Doubleday Books',
                num_pages: 336,
                publish_date: 'July 18, 2023',
                average_rating: 4.0,
                reviews: 6586,
                is_staff_pick: false,
                pic: require('../assets/images/covers/whitehead.jpg'),
            },
            {
                title: 'Happiness Falls',
                authors: 'Angie Kim',
                price: 26.04,
                publisher: 'Hogarth Press',
                num_pages: 400,
                publish_date: 'August 29, 2023',
                average_rating: 3.8,
                reviews: 12169,
                is_staff_pick: true,
                pic: require('../assets/images/covers/kim.jpg'),
            },
        ],
    },
    agathe: {
        query: 'Find a book for my best friend, she loves Agathe Christie',
        books: [
            {
                title: 'The Hound of the Baskervilles',
                authors: 'Arthur Conan Doyle',
                average_rating: 4.11,
                num_pages: 256,
                reviews: 112655,
                publisher: 'Penguin Books',
                price: 12.99,
                pic: require('../assets/images/covers/hound.jpg'),
                is_staff_pick: true,
                publish_date: '10/31/1901',
            },
            {
                title: "The No. 1 Ladies' Detective Agency",
                authors: 'Alexander McCall Smith',
                average_rating: 3.78,
                num_pages: 235,
                reviews: 141479,
                publisher: 'Anchor',
                price: 11.99,
                pic: require('../assets/images/covers/numberone.jpg'),
                is_staff_pick: false,
                publish_date: '3/11/1998',
            },
            {
                title: 'Gone Girl',
                authors: 'Gillian Flynn',
                average_rating: 4.06,
                num_pages: 415,
                reviews: 2145425,
                publisher: 'Broadway Books',
                price: 13.99,
                pic: require('../assets/images/covers/gonegirl.jpg'),
                is_staff_pick: false,
                publish_date: '5/24/2012',
            },
            {
                title: "The Cuckoo's Calling",
                authors: 'Robert Galbraith (J.K. Rowling)',
                average_rating: 3.84,
                num_pages: 561,
                reviews: 606183,
                publisher: 'Mulholland Books',
                price: 14.99,
                pic: require('../assets/images/covers/cuckoo.jpg'),
                is_staff_pick: true,
                publish_date: '4/30/2013',
            },
            {
                title: 'The Woman in White',
                authors: 'Wilkie Collins',
                average_rating: 3.99,
                num_pages: 672,
                reviews: 158339,
                publisher: 'Penguin Classics',
                price: 10.99,
                pic: require('../assets/images/covers/woman.jpg'),
                is_staff_pick: false,
                publish_date: '1/19/1859',
            },
            {
                title: 'Big Little Lies',
                authors: 'Liane Moriarty',
                average_rating: 4.25,
                num_pages: 460,
                reviews: 664239,
                publisher: 'Berkley',
                price: 15.99,
                pic: require('../assets/images/covers/biglittlelies.jpg'),
                is_staff_pick: false,
                publish_date: '7/29/2014',
            },
            {
                title: 'In the Woods',
                authors: 'Tana French',
                average_rating: 3.75,
                num_pages: 429,
                reviews: 250636,
                publisher: 'Viking',
                price: 13.99,
                pic: require('../assets/images/covers/inthewoods.jpg'),
                is_staff_pick: true,
                publish_date: '8/4/2007',
            },
        ],
    },
    classic: {
        query: 'What is a must read classic book',
        books: [
            {
                title: 'Pride and Prejudice',
                authors: 'Jane Austen',
                average_rating: 4.26,
                num_pages: 279,
                reviews: 2749751,
                publisher: 'Penguin Classics',
                price: 12.99,
                pic: require('../assets/images/covers/austen.jpg'),
                is_staff_pick: true,
                publish_date: '1/28/1813',
            },
            {
                title: '1984',
                authors: 'George Orwell',
                average_rating: 4.18,
                num_pages: 328,
                reviews: 3352163,
                publisher: 'Penguin Books',
                price: 14.99,
                pic: require('../assets/images/covers/orwell.jpg'),
                is_staff_pick: false,
                publish_date: '6/8/1949',
            },
            {
                title: 'To Kill a Mockingbird',
                authors: 'Harper Lee',
                average_rating: 4.28,
                num_pages: 281,
                reviews: 4293710,
                publisher: 'Harper Perennial',
                price: 15.99,
                pic: require('../assets/images/covers/mockingbird.jpg'),
                is_staff_pick: true,
                publish_date: '7/11/1960',
            },
            {
                title: 'The Great Gatsby',
                authors: 'F. Scott Fitzgerald',
                average_rating: 3.94,
                num_pages: 180,
                reviews: 4242565,
                publisher: 'Scribner',
                price: 13.99,
                pic: require('../assets/images/covers/gatsby.jpg'),
                is_staff_pick: false,
                publish_date: '4/10/1925',
            },
            {
                title: 'Moby-Dick',
                authors: 'Herman Melville',
                average_rating: 3.51,
                num_pages: 720,
                reviews: 505295,
                publisher: 'Penguin Classics',
                price: 16.99,
                pic: require('../assets/images/covers/mobydick.jpg'),
                is_staff_pick: true,
                publish_date: '10/18/1851',
            },
        ],
    },
    zen: {
        query: 'What books can I read to feel more zen in life',
        books: [
            {
                title: 'The Art of Happiness',
                authors: 'Dalai Lama XIV, Howard Cutler',
                average_rating: 4.17,
                num_pages: 384,
                reviews: 358245,
                publisher: 'Riverhead Books',
                price: 15.99,
                pic: require('../assets/images/covers/dalai.jpg'),
                is_staff_pick: false,
                publish_date: '12/1/1998',
            },
            {
                title: 'The Miracle of Mindfulness',
                authors: 'Thich Nhat Hanh',
                average_rating: 4.27,
                num_pages: 160,
                reviews: 34986,
                publisher: 'Beacon Press',
                price: 11.99,
                pic: require('../assets/images/covers/thic.jpg'),
                is_staff_pick: true,
                publish_date: '5/1/1975',
            },
            {
                title: 'The Power of Now',
                authors: 'Eckhart Tolle',
                average_rating: 4.13,
                num_pages: 229,
                reviews: 320610,
                publisher: 'New World Library',
                price: 13.99,
                pic: require('../assets/images/covers/tolle.jpg'),
                is_staff_pick: false,
                publish_date: '8/19/1997',
            },
            {
                title: 'Siddhartha',
                authors: 'Hermann Hesse',
                average_rating: 4.01,
                num_pages: 160,
                reviews: 614499,
                publisher: 'Penguin Books',
                price: 10.99,
                pic: require('../assets/images/covers/siddhartha.jpg'),
                is_staff_pick: true,
                publish_date: '1922',
            },
            {
                title: "Zen Mind, Beginner's Mind",
                authors: 'Shunryu Suzuki, Trudy Dixon',
                average_rating: 4.24,
                num_pages: 138,
                reviews: 37082,
                publisher: 'Weatherhill',
                price: 12.99,
                pic: require('../assets/images/covers/zen.jpg'),
                is_staff_pick: false,
                publish_date: '1970',
            },
        ],
    },
    dad: {
        query: 'Best book on being a dad',
        books: [
            {
                title: 'The Expectant Father: The Ultimate Guide for Dads-to-Be',
                authors: 'Armin A. Brott, Jennifer Ash',
                average_rating: 4.03,
                num_pages: 352,
                reviews: 5252,
                publisher: 'Abbeville Press',
                price: 15.99,
                pic: require('../assets/images/covers/expectant.jpg'),
                is_staff_pick: false,
                publish_date: '5/1/1995',
            },
            {
                title: "Dude, You're Gonna Be a Dad!: How to Get (Both of You) Through the Next 9 Months",
                authors: 'John Pfeiffer',
                average_rating: 3.83,
                num_pages: 224,
                reviews: 1109,
                publisher: 'Adams Media',
                price: 12.99,
                pic: require('../assets/images/covers/gonnabea.jpg'),
                is_staff_pick: true,
                publish_date: '3/18/2011',
            },
            {
                title: "The New Dad's Survival Guide: Man-to-Man Advice for First-Time Fathers",
                authors: 'Scott Mactavish',
                average_rating: 3.83,
                num_pages: 224,
                reviews: 419,
                publisher: 'Little, Brown and Company',
                price: 13.99,
                pic: require('../assets/images/covers/survival.jpg'),
                is_staff_pick: false,
                publish_date: '4/9/2010',
            },
            {
                title: 'Be Prepared: A Practical Handbook for New Dads',
                authors: 'Gary Greenberg, Jeannie Hayden',
                average_rating: 4.08,
                num_pages: 240,
                reviews: 1513,
                publisher: 'Simon Schuster',
                price: 14.99,
                pic: require('../assets/images/covers/prepared.jpg'),
                is_staff_pick: true,
                publish_date: '5/5/2004',
            },
            {
                title: 'Strong Fathers, Strong Daughters: 10 Secrets Every Father Should Know',
                authors: 'Meg Meeker',
                average_rating: 4.06,
                num_pages: 294,
                reviews: 17529,
                publisher: 'Ballantine Books',
                price: 15.99,
                pic: require('../assets/images/covers/strong.jpg'),
                is_staff_pick: false,
                publish_date: '1/3/2006',
            },
        ],
    },
};
